### ISSUE TITLE
query params: add single-value parameters, always include default theme

### ISSUE THREAD

**Issue by x1B** [jpommerening/laxar-loader#1]
- [x] because webpack loader utils has its own opinion on `&themes=v1,v2`, we need to use `&theme[]=v1&theme[]=v2` -- for single values we should simplify this by supporting dedicated parameter names (`flow`, `theme`).

- [x] currently, we should implicitly include the default theme, because apps will pretty much always break without it. Eventually, we should add a "cascade" that fills missing themed assets with default theme assets (only if the default theme is not included anyway).

**Comment by jpommerening** [comment]
released as `v0.2.0`
