### ISSUE TITLE
controls/widgets: support embeding/listing of assets

### ISSUE THREAD

**Issue by x1B** [jpommerening/laxar-loader#2]
The widget/control descriptors should support 4 optional fields for embedding and/or referencing assets into the artifacts bundle:

- [ ] `assets` additional asset content (e.g. a `messages.json` file for axternalized strings).
- [ ] `assetUrls` additional asset content for lazy-loading (e.g. a `messages.en.json` file for localization strings).
- [ ] `assetsForTheme` additional theme assets (in addition to the HTML template)
- [ ] `assetUrlsForTheme` additional theme asset references (in addition to the CSS)

**Comment by jpommerening** [comment]
released as `v0.2.0`
