### ISSUE TITLE
feature request: allow to load widget directly, to produce widget-specific artifacts

### ISSUE THREAD

**Issue by x1B** [jpommerening/laxar-loader#4]
We have two scenarios where we'd like to side-step the flow and to directly bootstrap LaxarJS for a specific widget:

- [ ] *widget testing:* here, we'd just like to include the default theme and the widget under test, along with its (transitive) controls,

- [ ] *direct widget embedding:* when integrating into an existing portal that has its own navigation, we'd sometimes like to just render a standalone widget, without the flow/page machinery.

**Comment by jpommerening** [comment]
implemented in `v0.3.0` 👍
